### ISSUE TITLE
Error creating comments. 

### ISSUE THREAD

**Issue by ghudachek** [ghudachek/WouldYouRather#3]
# PROJECT ISSUE TICKET

> Copy and paste the raw MD code of this template **into an issue ticket in your project repo**, then replace the quote blocks with your detailed, clear descriptions.

## Unexpected Behavior

Cannot create new comments

## Expected Behavior

to create a new comment

## Reproduce the Error

```md
1. Clone this repo.
2. Run `npm start`.
3. log in user: admin pass: hello
4. on home page write in a comment and hit send
5. open network page and see error on comments.
```

## Documentation

![image](https://user-images.githubusercontent.com/57376725/113436062-a318ce00-93a9-11eb-820b-a824e45838d0.png)

```md
Completed 400 Bad Request in 2ms (ActiveRecord: 0.3ms | Allocations: 701)



ActionController::ParameterMissing (param is missing or the value is empty: post
Did you mean?  controller
               question_id
               action
               comment):

app/controllers/comments_controller.rb:51:in `comment_params'
app/controllers/comments_controller.rb:19:in `create'
```

## Attempted Resolution

I added authorize user to my controllers so that the user__id would be filled and attempted to add the questions id throught the map function in the Home.jsx line 46 and CommentCreate.jsx line 8.. Not sure this is working right either.

**Comment by ghudachek** [comment]
Code needs to be pulled from dev branch**
